### ISSUE TITLE
Indeterministic results from diff_unicode

### ISSUE THREAD

**Issue by EmilStenstrom** [JoshData/fast_diff_match_patch#1]
I'm using Python 2.7.6 and was hoping this library would be a speedup compared with diff_match_patch from pypi. Unfortunately, I get different results back for each call to diff_unicode:

``` python
>>> from diff_match_patch import diff_unicode
>>> diff_unicode(u"testing", u"test", timelimit=0, checklines=False, cleanup_semantic=False, counts_only=False)
[('-', u'test'), ('=', u'test\x00\u7400\u2773\x00\uc160\u0123')]
>>> diff_unicode(u"testing", u"test", timelimit=0, checklines=False, cleanup_semantic=False, counts_only=False)
[('+', u'test'), ('=', u'testin')]
>>> diff_unicode(u"testing", u"test", timelimit=0, checklines=False, cleanup_semantic=False, counts_only=False)
[('=', u'te'), ('-', u'ing'), ('+', u'\x00\u7400\u2773'), ('=', u'\x01'), ('-', u'\u275f'), ('+', u'\uebd0\u012e\x01\x00\uc180')]
```

Sounds like a problem way down C++ lane. Any ideas? Would very much like the speedup this library could give me.

**Comment by JoshData** [comment]
Did you rebuild the binaries (and not use one of the pre-built ones) by any chance?

**Comment by EmilStenstrom** [comment]
I used `pip install diff_match_patch_python==1.0.1`. I guess that rebuilds the binaries?

**Comment by JoshData** [comment]
Yeah.

I only get the first output. I'll have to think about it --- no idea off hand why it would do that.

**Comment by EmilStenstrom** [comment]
For reference, here's the build log: http://dpaste.com/05AGNJP

And I'm on a Mac:

```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

**Comment by hundt** [comment]
@EmilStenstrom I suspect you have the same problem I have (also on a Mac): a "narrow" build of Python which internally encodes strings using UTF-16 (2 bytes per character), combined with a system setting of `wchar_t` as 4 bytes. Since `interface.cpp` appears to read the Python string directly into a `wstring` (array of `wchar_t`s) this results in the input to the library being corrupted.

@JoshData The only way I can think of to fix this is to transcode the input into `std::wstring` in this case as it appears that diff-match-patch-cpp-stl only works with `std::wstring` and `std::string`.

**Comment by JoshData** [comment]
Interesting. Is there a way I can reproduce this on Ubuntu (or an OS I can spin up on a cloud machine)? Otherwise I don't have a good way to fix this. (But am happy to accept a PR to fix it.)

**Comment by hundt** [comment]
You can make a narrow build of Python like so:

```
wget https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz
tar xf Python-2.7.11.tgz
cd Python-2.7.11/
./configure --enable-unicode=ucs2 && make
```

You can verify that the resulting binary is narrow by doing

```
./python -c "import sysconfig; print sysconfig.get_config_var('Py_UNICODE_SIZE')"
```

If it prints "2" it is narrow; if it prints "4" it is wide.

From there you will need to recompile your module against the narrow build. I'm not familiar enough with developing python packages to know the most convenient way to do so. But once you have a narrow Python with your module installed, you will see the behavior just by running your test.py file.

**Comment by EmilStenstrom** [comment]
Excellent @hundt, you are completely right that I have a narrow build. Seems that this is the default on Mac.

**Comment by JoshData** [comment]
Could you both try it now (build from source)?

**Comment by hundt** [comment]
Thanks for addressing this so quickly, Josh!

There were a couple issues with your update:
- You need to convert back to Python strings before returning
- You didn't null-terminate the input when you converted

so I made a pull request addressing them. I also added some comments about the subtleties of transcoding and a test to help demonstrate them.

I tested my new code on wide and narrow builds of Python 2.7 but I haven't tried Python 3.

**Comment by JoshData** [comment]
Great. I merged it! (It worked for me in Py 3 on Ubuntu, where it's supposedly always `wchar_t` on all builds.)

**Comment by EmilStenstrom** [comment]
I can confirm that this works on my Python 2.7 narrow build python too. Thanks for not forgetting about my old bug report! :)

Will you make a new release to pypi to make this easier to get installed?

**Comment by JoshData** [comment]
Good point. I just uploaded it as version 1.0.2. Lemme know if that works!

**Comment by EmilStenstrom** [comment]
The PyPi version works great with both python 2.7 and python 3.4. Thanks!

**Comment by hundt** [comment]
Works for me now; thanks!
