### ISSUE TITLE
Package republished as fast-diff-match by another maintainer?

### ISSUE THREAD

**Issue by jcushman** [JoshData/fast_diff_match_patch#12]
Heads up that this package has been republished by another PyPI user at https://pypi.org/project/fast-diff-match/ , though it still links to this Github repo and Author contact and so on. (And still imports as `diff_match_patch`, so I assume isn't related to fixing the name collision in #4.)

Also for what it's worth that republished version only includes Mac packages, so doesn't install on other OSes.

Not sure what's going on with that, just thought I'd flag it since it's a little confusing for someone looking for a python DMP library.

**Comment by JoshData** [comment]
Thanks for the heads up. This isn't the first time one of my packages was re-posted, and to me this is a security/impersonation issue, but pypi didn't get back to me on the other one so I assume there is nothing to be done here.
