### ISSUE TITLE
How to access Match_Threshold, Match_Distance during python call?

### ISSUE THREAD

**Issue by sreeni5493** [JoshData/fast_diff_match_patch#15]
```
import diff_match_patch as dmp
dmp.match_main('asdf', 'd', 0)
print(dmp.Match_Threshold)
```

I want to set Match Distance to 0 so that this returns -1 whereas it returns 0 and I am unable to access dmp.Match_Threshold. Above print statement will throw an error if I want to see what value is assigned.

How can I access Match_Threshold and Match_Distance values in python code. Should I change something inside the C++ code?

**Comment by JoshData** [comment]
They can be set using keyword arguments. You'll have to read the C++ to see. If you use it, I would appreciate it if you would open a pull request adding documentation to the README for all of the match functionality, since it was added in #8 without any documentation.
