### ISSUE TITLE
Missing API?

### ISSUE THREAD

**Issue by mustafa0x** [JoshData/fast_diff_match_patch#17]
https://github.com/google/diff-match-patch/wiki/API

It seems like only `diff` and `match_main` are supported?

I did look at https://github.com/leutloff/diff-match-patch-cpp-stl/blob/master/diff_match_patch.h and it seems to contain the API functions, but I don't see them in this wrapper.

If this wrapper is limited to `diff` and `match_main` perhaps mention that in the README?

**Comment by JoshData** [comment]
I only implemented what I needed. I would accept a pull request that implements the others (and includes documentation in the README).

**Comment by mustafa0x** [comment]
Thanks for the reply! Unfortunately I have insufficient C++ knowledge, but maybe someone else will volunteer.
