### ISSUE TITLE
Publish Windows wheels for Python 3.12

### ISSUE THREAD

**Issue by codeofdusk** [JoshData/fast_diff_match_patch#25]
Python 3.12 is slated for release next week, and the Python core developers [encourage package developers to publish updated wheels in preparation](https://www.python.org/downloads/release/python-3120rc3/). Please publish Python 3.12 (win32 and amd64) wheels to PyPI.

**Comment by codeofdusk** [comment]
CC @JoshData.

**Comment by JoshData** [comment]
Thanks. I added the wheels to the existing release on PyPi. (Hopefully it works fine.)

**Comment by codeofdusk** [comment]
Works for me, thanks!

**Comment by JoshData** [comment]
Thanks for letting me know!
