### ISSUE TITLE
non ascii characters on windows

### ISSUE THREAD

**Issue by Ymiros0** [JoshData/fast_diff_match_patch#26]
Nothing too major ig, but at least on windows 10 non ascii characters seem to break when this module is trying to print them, the diff calculation seems to work fine, but when you ask the function to print the string back, non ascii characters break, eg:
```
>>> print(diff('Mögen','Mägen',as_patch=True))
@@ -1,5 +1,5 @@
 M
-%C3%B6
+%C3%A4
 gen
```

**Comment by JoshData** [comment]
I'm not actively maintaining the project but I'll leave the issue open in case anyone can find the problem (although I'm not sure this is a bug, it may be a limitation of how Python on Windows stores Unicode).

**Comment by JoshData** [comment]
I think this may be the intended behavior of the underlying diff_match_patch library, and it may be based on existing conventions for patch files in the Linux world.
