### ISSUE TITLE
Name collision on PyPI

### ISSUE THREAD

**Issue by jcushman** [JoshData/fast_diff_match_patch#4]
Just a note that this package name collides with https://pypi.python.org/pypi/diff-match-patch/ -- that is, both of them come in under `import diff_match_patch`, but have different APIs.

This makes it impossible to use both in the same project, or to use any combination of libraries that depend on both. As a specific usecase, I was working on a script using https://github.com/sachinrekhi/richtextpy, which depends on the other lib, and then tried to use this library for some fast diffing in another part of the script, and as far as I can tell that's not possible. (Maybe by installing this library outside of sys.path and doing some clever import magic?)

I realize this is no one's problem but my own. :) If you're open to working on it, though, it might be nice to also publish this with an alternate package name like `fast_diff_match_patch`, since the colliding library is just a straight packaging of the original google script.

Thanks!

**Comment by JoshData** [comment]
Hey, yes, I'm totally open to changing the names to fix that. This has been bothering me too. If you submit a PR renaming both the module (i.e. the import name) and the pypi package (in setup.py) like you said, I'll take care of fixing how it's published on pypi (and I'll rename this repo to match too).

(You might be interested in https://github.com/joshdata/jot by the way.)

**Comment by rmorshea** [comment]
This seems to have been fixed.

**Comment by JoshData** [comment]
It's now uploaded to PyPi at https://pypi.org/project/fast-diff-match-patch/ !
