### ISSUE TITLE
This library isn't binary safe. 0x00 can't be in the string.

### ISSUE THREAD

**Issue by myrfy001** [JoshData/fast_diff_match_patch#5]
I use Python 2.7 and the input can't contain a 0x00 char.

**Comment by christian-storm** [comment]
Same here but with python 3.

**Comment by JoshData** [comment]
In the latest release (today), this seems to be working with strings in Py 3, but not with bytes yet.

**Comment by JoshData** [comment]
Hopefully fixed in https://github.com/JoshData/fast_diff_match_patch/commit/07f19e6b4b9488599a85b3318840183d92e48f3e.
