### ISSUE TITLE
Off by one error?

### ISSUE THREAD

**Issue by christian-storm** [JoshData/fast_diff_match_patch#6]
I found what seems to be a corner case.  When I run diff with just one substitution I get:
diff('xxx','XxX') -> [('-', 3), ('+', 3)] 
instead of  [('-', 1), ('+', 1), ('=', 1), ('+', 1)]

Bug?

```
from diff_match_patch import diff

assert diff('xxxx','XxxX') == [('-', 2), ('+', 1), ('=', 2), ('+', 1)]
assert diff('xxx','XxX') == [('-', 1), ('+', 1), ('=', 1), ('+', 1)]
```

**Comment by JoshData** [comment]
There are sometimes several valid diffs for a given input. -3 +3 is a valid diff --- it says delete everything and insert the whole right document. It's not helpful, but it's valid. The DMP algorithm sometimes yields that when it thinks it's the preferable diff.

**Comment by christian-storm** [comment]
Thanks for your prompt reply.  Do you know of any settings that discourage that?  I looked through the code and found these:
```
  diff_match_patch() :
    Diff_Timeout(1.0f),
    Diff_EditCost(4),
    Match_Threshold(0.5f),
    Match_Distance(1000),
    Patch_DeleteThreshold(0.5f),
    Patch_Margin(4),
    Match_MaxBits(32) {
  }
```

**Comment by christian-storm** [comment]
Took a crack at trying to figure it out but couldn't.
