### ISSUE TITLE
ImportError: cannot import name diff

### ISSUE THREAD

**Issue by ndvbd** [JoshData/fast_diff_match_patch#9]
I have python 2.7

And I get
`ImportError: cannot import name diff`

when I do: 
`from diff_match_patch import diff`

I installed like this:

`sudo pip install diff_match_patch_python`

**Comment by jcushman** [comment]
This will happen if you also have `pip install diff_match_patch` -- see #4.

**Comment by JoshData** [comment]
The package has been renamed and is now https://pypi.org/project/fast-diff-match-patch/ to avoid this issue.
